### ISSUE TITLE
Assalomu Alaykum, AnsorMed saytining navbar qismidagi linklar qora va fontlari ulangan holda bo'lishi kerak edi. Iltimos to'g'irlab qo'ysangiz

### ISSUE THREAD

**Issue by FakhriddinovSh** [abdulvakhid/ansormed#1]
![ansor-1](https://user-images.githubusercontent.com/94530124/170103195-026a4fe1-9e85-4368-8ed4-41dddcec239f.png)

**Comment by abdulvakhid** [comment]
Volekum assalom,  Assalomu alekum siz aytgan muammolar bartaraf qilindi.
![#1](https://user-images.githubusercontent.com/93217687/170175380-b2bb9607-4a86-4e39-a09e-1fc187617af5.png)
