### ISSUE TITLE
Assalomu Alaykum, Hero section ichidagi h1 ga rang va p ga width berish kerak edi Maketdagidek, Iltimos to'girlab qoysangiz

### ISSUE THREAD

**Issue by FakhriddinovSh** [abdulvakhid/ansormed#2]
![ansor-2](https://user-images.githubusercontent.com/94530124/170103522-0b435750-ad21-4b68-9306-472d9ea973bd.png)

**Comment by abdulvakhid** [comment]
Volekum assalom, Assalomu aleykum muammo hal qilindi
![#2](https://user-images.githubusercontent.com/93217687/170175886-74cf2660-6fee-4742-8804-f5642570df27.png)
