### ISSUE TITLE
Assalomu Alaykum, Img va textlar orasidagi masofa  64px bo'lishi kerak edi, Sizda bu 77px ni ko'rsatmoqda. Iltimos to'g'rlab qoysangiz

### ISSUE THREAD

**Issue by FakhriddinovSh** [abdulvakhid/ansormed#3]
![ansor-3](https://user-images.githubusercontent.com/94530124/170103858-24310913-7f59-40d8-b7d4-d966868937fc.png)

**Comment by abdulvakhid** [comment]
volekum assalom, Assalomu alekum xatolarni bartaraf qildik

**Comment by abdulvakhid** [comment]
volekum assalom, Assalomu alekum xatolarni bartaraf qildik
![#3](https://user-images.githubusercontent.com/93217687/170176577-1b921ec8-d797-4e9c-a7f3-d87717aaa4ae.png)
