### ISSUE TITLE
Assalomu Alaykum, Title ga padding-top 64px berish kerak edi Maketdagidek. Siz bergan qiymat 44px ko'rsatmoqda. Iltimos to'g'rilab qo'ysangiz 

### ISSUE THREAD

**Issue by FakhriddinovSh** [abdulvakhid/ansormed#4]
![ansor-4](https://user-images.githubusercontent.com/94530124/170104343-e214dcde-116b-4be2-888a-611d8b0536ce.png)

**Comment by abdulvakhid** [comment]
Assalomu aleykum, margin top to'g'rilandi
