### ISSUE TITLE
Assalomu Alaykum. Footer qismidagi linklar hover bo'lganida pastki chiziq bo'lmasligi kerak edi. Iltimos to'grlab qoysangiz

### ISSUE THREAD

**Issue by FakhriddinovSh** [abdulvakhid/ansormed#5]
![ansor-5](https://user-images.githubusercontent.com/94530124/170104604-64a1df40-5361-4bc7-88f1-e1cf9ca692bb.png)

**Comment by abdulvakhid** [comment]
Assalomu alekum, chiziqlar olib tashlandi
